### PR TITLE
⛅ Allow base/integration tests to run in PSI + AWS

### LINKED ISSUE #844: Integration tests are flaky/slow on hosts without nested virtualization
On hosts without nested virt, such as AWS instances, the integration tests are often much slower and they sometimes fail on ssh connections. Here's a recent one from Fedora 32 on AWS:

```
[2020-07-10T12:44:51.003Z] [1;32m🚀 Booting the image with libvirt[0m
[2020-07-10T12:44:51.856Z] WARNING  KVM acceleration not available, using 'qemu'
[2020-07-10T12:44:52.260Z] 
[2020-07-10T12:44:52.260Z] Starting install...
[2020-07-10T12:44:52.260Z] Domain creation completed.
[2020-07-10T12:44:52.260Z] [1;32m💻 Waiting for the instance to make a DHCP request.[0m
[2020-07-10T12:46:03.124Z] Found instance address: 192.168.122.57
[2020-07-10T12:46:03.124Z] [1;32m⏱ Waiting for instance to respond to ssh[0m
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] Retrying in 5 seconds...
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.124Z] Retrying in 5 seconds...
[2020-07-10T12:46:03.124Z] # 192.168.122.57:22 SSH-2.0-OpenSSH_8.3
[2020-07-10T12:46:03.528Z] # 192.168.122.57:22 SSH-2.0-OpenSSH_8.3
[2020-07-10T12:46:03.528Z] # 192.168.122.57:22 SSH-2.0-OpenSSH_8.3
[2020-07-10T12:46:03.528Z] # 192.168.122.57:22 SSH-2.0-OpenSSH_8.3
[2020-07-10T12:46:03.528Z] # 192.168.122.57:22 SSH-2.0-OpenSSH_8.3
[2020-07-10T12:46:03.528Z] SSH is up!
[2020-07-10T12:46:03.642Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.642Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.642Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.642Z] write (192.168.122.57): Connection refused
[2020-07-10T12:46:03.642Z] write (192.168.122.57): Connection refused
```

We need a more reliable method of using ssh to connect and it might be good to avoid dhcp and use a static address instead.

### LINKED ISSUE #847: Fedora 31 installs NetworkManager, which breaks cloud-init
NetworkManager in Fedora 31 makes cloud-init upset and it will not write the network configuration as it should. The Fedora cloud team fixes this by [explicitly removing NetworkManager](https://pagure.io/fork/jdoss/fedora-kickstarts/c/d95b59ac3beca4a95cef40306e4e598fe1eaaaaf).

For Fedora 31, we need to install `network-scripts` so that cloud-init has access to all of the stuff in `/etc/sysconfig/network-scripts` that it needs to manage the network configuration.

### PR DESCRIPTION
**Pull request by major**
Make it easier to handle PSI outages or those times when PSI is overloaded with jobs by allowing base and integration tests to run on PSI OpenStack and AWS.

Also increase the reliability and speed of the integration tests that are booted locally by using a static IP address configuration. Keep checking for the smoke test file repeatedly without messing around with ssh key scanning. This helps when ssh comes up on an instance and then goes back down again.

Fixes #844.
Fixes #847.

### CODE REVIEW

**Comment by major** [comment]
Opened #844 since it seems to show up at AWS fairly often.

**Comment by major** [comment]
Bah, osbuild had issues downloading from mirrors. That's osbuild/osbuild#454. I've just put in #846 which may help out with this and #845.

File: schutzbot/deploy.sh [hunk 1]
```diff
@@ -21,6 +21,12 @@ function retry {
 # Get OS details.
 source /etc/os-release
 
+# Register RHEL if we are provided with a registration script.
+if [[ -n "${RHN_REGISTRATION_SCRIPT:-}" ]] && ! sudo subscription-manager status; then
+    sudo chmod +x $RHN_REGISTRATION_SCRIPT
```
Comment (teg) [inline schutzbot/deploy.sh:26]: How come the script does not already have `+x`?

Comment (major) [reply schutzbot/deploy.sh:26]: Jenkins dumps it on the host as a secret, so it's dumped as a plain file without `-x` set.

File: internal/distro/fedora31/distro.go [hunk 2]
```diff
@@ -207,6 +207,7 @@ func New() *Fedora31 {
 			"cloud-init",
 			"checkpolicy",
 			"net-tools",
+			"network-scripts",
```
Comment (teg) [inline internal/distro/fedora31/distro.go:210]: In the linked RHBZ they talk about adding NetworkManager, but in the github issue, you explain that NM breaks cloud-init. I guess in the end they ended up with network-scripts instead. I think a link to the fedora31 qcow2 .ks as the authorotative source would be good for this PR. Also: test cases must be regenerated.

Comment (major) [reply internal/distro/fedora31/distro.go]: Yup, I've re-read the bugs and removed that adjustment now.

**Comment by major** [comment]
Other than #798, the test run looks good!

**Comment by major** [comment]
@teg As you noted last week, I forced use of AWS for these jobs with the `aws` label since I wanted to test all of the jobs at AWS + PSI.

Either we can leave it as is (AWS only for these jobs) and and remove it in a follow-on commit or we can change it now and wait for CI to run again.

**Comment by teg** [comment]
I'm fine with either. Whether tests run in AWS or PSI makes no difference (except for the price), no? Up to you :)

**Comment by major** [comment]
@teg Okay, I'll merge and follow up with a commit to allow it to run on AWS or PSI.
