### PR TITLE
Worker: report stages status after RunOSBuild

### LINKED ISSUE #1584: Print stages result from osbuild inside the worker's journal
In the file cmd/osbuild-worker/jobimpl-osbuild.go we find that handles the call to RunOSBuild and gets the data.

```

	// Run osbuild and handle two kinds of errors
	osbuildJobResult.OSBuildOutput, err = RunOSBuild(args.Manifest, impl.Store, outputDirectory, exports, os.Stderr)
	// First handle the case when "running" osbuild failed
	if err != nil {
		return err
	}
	// Second handle the case when the build failed, but osbuild finished successfully
	if !osbuildJobResult.OSBuildOutput.Success {
		return nil
	}
```

I think we could improve the behavior of this code chunk by adding detail printing about the stages. What I have in mind is to output a stage per line in green color when the stage is successful and a red multiline chunk with the reason of the failure when the stage errors out.

### PR DESCRIPTION
**Pull request by lavocatt**
To help along with debugging, this commit makes the worker able to print
the status of the different stages with a oneliner for each successfull
stages and a detailed message for failed ones.

Sample output:
Jul 23[..]: Build stages results:
Jul 23[..]: org.osbuild.rpm  success
Jul 23[..]: org.osbuild.selinux  success
Jul 23[..]: Stages results:
Jul 23[..]: org.osbuild.rpm  success
Jul 23[..]: org.osbuild.fix-bls  success
Jul 23[..]: org.osbuild.fstab  success
Jul 23[..]: org.osbuild.grub2  success
Jul 23[..]: org.osbuild.locale  success
Jul 23[..]: org.osbuild.timezone  success
Jul 23[..]: org.osbuild.users failure:
Jul 23[..]:  [/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping
Jul 23[..]: All rules containing unresolvable specifiers will be skipped.
Jul 23[..]: Failed to create file /sys/fs/selinux/checkreqprot: Read-only file system
Jul 23[..]: useradd: group 'toto' does not exist

Fixes #1584

This pull request includes:

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] create a file in [news/unreleased](https://github.com/osbuild/osbuild-composer/tree/main/docs/news/unreleased) directory if this change should be mentioned in the release news
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

### CODE REVIEW

**Review by achilleas-k — COMMENTED** [review]
Very nice!  Would `log.Print` be more appropriate?  It looks like that's what we use to print other status messages.

**Comment by lavocatt** [comment]
> Very nice! Would `log.Print` be more appropriate? It looks like that's what we use to print other status messages.

Thanks for the review. Yes it could be nicer indeed. But the default loger does not expose a stderr logging without quitting the execution. So I'll need to instantiate a new logger for the case where I want to log to stderr.

File: cmd/osbuild-worker/jobimpl-osbuild.go [hunk 1]
```diff
@@ -96,6 +96,29 @@ func (impl *OSBuildJobImpl) Run(job worker.Job) error {
 	if err != nil {
 		return err
 	}
+
+	fmt.Println("Build stages results:")
+
+	// Include the build stages output inside the worker's logs.
+	for _, stage := range osbuildJobResult.OSBuildOutput.Build.Stages {
```
Comment (ondrejbudai) [inline cmd/osbuild-worker/jobimpl-osbuild.go:103]: @achilleas-k This doesn't work for v2 manifests, does it?

Comment (Gundersanne) [reply cmd/osbuild-worker/jobimpl-osbuild.go:103]: The worker only depends on osbuild1 though. Is a bunch of osbuild2 output ignored now when returning the jobresult, and just what's overlapped in json tags between v1 and v2 results?

Comment (achilleas-k) [reply cmd/osbuild-worker/jobimpl-osbuild.go:105]: osbuild2 output gets unmarshalled into an osbuild1.Result object automatically.  @ondrejbudai remember this? :)

https://github.com/osbuild/osbuild-composer/blob/1abd9a11924cf20a2a3b9e2cbe173dae4b614005/internal/osbuild1/result.go#L53

Comment (achilleas-k) [reply cmd/osbuild-worker/jobimpl-osbuild.go:105]: Sidenote: At some point (soon) I think we should change this to use v2 types primarily at which point we would need to change occurrences like this as well.

**Review by achilleas-k — DISMISSED** [review]

File: cmd/osbuild-worker/jobimpl-osbuild.go [hunk 2]
```diff
@@ -37,6 +37,8 @@ func appendTargetError(res *worker.OSBuildJobResult, err error) {
 }
 
 func (impl *OSBuildJobImpl) Run(job worker.Job) error {
+	errorLog := log.New(os.Stderr, "", 0)
+	errorLog.SetFlags(log.Ldate | log.Ltime)
```
Comment (ondrejbudai) [inline cmd/osbuild-worker/jobimpl-osbuild.go:41]: is this really needed? The standard logger is defined in this way:

```golang
const (
	LstdFlags     = Ldate | Ltime // initial values for the standard logger
)
var std = New(os.Stderr, "", LstdFlags)
```

Looks like we are instantiating the exact same thing.

See https://github.com/golang/go/blob/7ba8e796c91eaf4befcacc4d24127ae54475d6a5/src/log/log.go#L317

**Review by ondrejbudai — CHANGES_REQUESTED** [review]

File: cmd/osbuild-worker/jobimpl-osbuild.go (hunk 1 above)
Comment (ondrejbudai) [reply cmd/osbuild-worker/jobimpl-osbuild.go:105]: Ah, I remember now, we need to rewrite that at some point but this PR is definitely a good step forward, thanks! :)

File: cmd/osbuild-worker/jobimpl-osbuild.go (hunk 2 above)
Comment (lavocatt) [reply cmd/osbuild-worker/jobimpl-osbuild.go:41]: Oh! Indeed! Imma revert this. Thanks.

**Review by ondrejbudai — APPROVED** [review]
Looks good, thank you for looking into this!

**Review by achilleas-k — APPROVED** [review]

**Review by teg — COMMENTED** [review]
Too late to the party, but: love this! Going to help us a lot I think :)
