### PR TITLE
Specify image filenames in upload targets

### LINKED ISSUE #348: Local target only supports uploading one file
https://github.com/osbuild/osbuild-composer/pull/347 changes the local upload target to only upload a single file from the result directory. That's a bit smelly (we ought to know the name) and will not work for pipelines that have multiple outputs (if we ever have those).

I see a few options of fixing that:
1. Include the filename(s) to upload in the UploadTarget that's passed to the job.
2. Base the filename on the compose id (this only works for one and might be a layer violation: `distro` package doesn't necessarily know the compose id yet)
3. Upload all files

Curious to hear your thoughts.

### PR DESCRIPTION
**Pull request by teg**
Drop any assumptions about the name or number of output files that osbuild produces from the worker.

Inspired by #370, fixes #348.

### CODE REVIEW

File: internal/weldr/upload.go [hunk 1]
```diff
@@ -99,32 +118,26 @@ func TargetsToUploadResponses(targets []*target.Target) []UploadResponse {
 	return uploads
 }
 
-func UploadRequestToTarget(u UploadRequest, filename string) (*target.Target, error) {
```
Comment (larskarlitski) [inline internal/weldr/upload.go]: Hm, you added the parameter in the previous commit, just to remove it again here. It is never used.

Comment (teg) [reply internal/weldr/upload.go]: Ah, a rebase gone awry. Thanks! Fixed and pushed two natural follow-ups on top.
