### PR TITLE
Image installer on aarch64

### LINKED ISSUE #1903: [RHEL-9] Missing support for image-installer image type on aarch64
**Description**
Support for building `image-installer` image type is missing on RHEL-9 for aarch64.

**Environment**
 * OS version: RHEL-9.0.0
 * osbuild-composer version: osbuild-composer-33.3-1.el9_b.aarch64

**To Reproduce**
Run `composer-cli compose types` -> `image-installer` type is missing.

**Expected behavior**
Run `composer-cli compose types` -> `image-installer` type is listed and can be built.

**Additional info**
@achilleas-k agreed on adding the required support while doing the RHEL 9 definitions.

### PR DESCRIPTION
**Pull request by achilleas-k**
- Added image installer to aarch64 for RHEL 8.6 (CS8) and RHEL 9.0 (CS9)
- Fixed anaconda package sets
- Added manifests

~~Keeping as draft until I boot test them locally since we don't have aarch64 CI for installers (openstack)~~

Tested working locally.

Fixes #1903

### CODE REVIEW

File: internal/distro/rhel90/package_sets.go [hunk 1]
```diff
@@ -969,9 +968,7 @@ func anacondaPackageSet(t *imageType) rpmmd.PackageSet {
 			"glibc-all-langpacks",
 			"gnome-kiosk",
 			"google-noto-sans-cjk-ttc-fonts",
-			"grub2-efi-x64-cdboot",
```
Comment (gicmo) [inline internal/distro/rhel90/package_sets.go:972]: Is this pulled in via "grub2-tools-efi", or did this just get removed? Could maybe use a comment in the commit message.

File: internal/distro/rhel86/package_sets.go [hunk 2]
```diff
@@ -661,6 +661,7 @@ func anacondaPackageSet(t *imageType) rpmmd.PackageSet {
 			"librsvg2",
 			"linux-firmware",
 			"lklug-fonts",
+			"lldpad",
```
Comment (gicmo) [inline internal/distro/rhel86/package_sets.go:661]: Just out of curiosity: Is this only required for dracut on arm64 or was the whole image-installer broken on 8.6 until now?

**Review by gicmo — COMMENTED** [review]
Looks great. Only a small comment about some packages.

File: internal/distro/rhel90/package_sets.go [hunk 3]
```diff
@@ -1048,15 +1044,13 @@ func anacondaPackageSet(t *imageType) rpmmd.PackageSet {
...
 			"sg3_utils",
-			"shim-x64",
 			"sil-abyssinica-fonts",
 			"sil-padauk-fonts",
 			"sil-scheherazade-fonts",
 			"smartmontools",
 			"smc-meera-fonts",
 			"spice-vdagent",
 			"strace",
-			"syslinux",
```
[the remark this answers is not in the document]
Comment (achilleas-k) [reply internal/distro/rhel90/package_sets.go:1059]: Already defined in the [anacondaBootPackageSet for x86](https://github.com/achilleas-k/osbuild-composer/blob/836fee7f39541cd544880abcba8c406dba5b580e/internal/distro/rhel90/package_sets.go#L123-L124) that already gets [merged in](https://github.com/achilleas-k/osbuild-composer/blob/836fee7f39541cd544880abcba8c406dba5b580e/internal/distro/rhel90/package_sets.go#L1078) to this one.

File: internal/distro/rhel90/package_sets.go (hunk 1 above)
Comment (achilleas-k) [reply internal/distro/rhel90/package_sets.go:972]: Same story with syslinux above: [anacondaBootPackageSet for x86](https://github.com/achilleas-k/osbuild-composer/blob/836fee7f39541cd544880abcba8c406dba5b580e/internal/distro/rhel90/package_sets.go#L119)

File: internal/distro/rhel86/package_sets.go (hunk 2 above)
Comment (achilleas-k) [reply internal/distro/rhel86/package_sets.go:661]: It's required by both.

Had to look into this to make sure if it needs to be included.  I added it because it was mentioned in the failing dracut stage, but it's actually pulled in by `fcoe-utils`, which was already there on 8.6 and I had to add to 9.0.

I can remove it from both since it's a dependency.

**Comment by teg** [comment]
Only CS9 is red, which is expected. I'm ok with admin-merge.

**Comment by gicmo** [comment]
> Only CS9 is red, which is expected. I'm ok with admin-merge.

Still need to coordinate with @ondrejbudai and the PR for the iso size.

**Comment by gicmo** [comment]
All green except koji integration on CS9, merging.
