### PR TITLE
tests/compose: use qcow2 rather than ami for tests

### LINKED ISSUE #693: ppc64le: osbuild-tests failure
From RHEL 8 on ppc64le:

```
TASK [Run osbuild-tests test] **************************************************
Friday 29 May 2020  12:55:02 -0400 (0:00:00.670)       0:10:51.753 ************ 
fatal: [localhost]: FAILED! => changed=true 
  cmd:
  - /usr/libexec/tests/osbuild-composer/osbuild-tests
  - -test.v
  delta: '0:00:22.795913'
  end: '2020-05-29 12:55:25.418691'
  msg: non-zero return code
  rc: 1
  start: '2020-05-29 12:55:02.622778'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    === RUN   TestComposeCommands
    --- FAIL: TestComposeCommands (0.71s)
        main_test.go:257:
                    Error Trace:    main_test.go:257
                                                            main_test.go:40
                    Error:          Received unexpected error:
                                    exit status 1
                    Test:           TestComposeCommands
                    Messages:       Command failed: exit status 1
    === RUN   TestEverything
    --- PASS: TestEverything (21.18s)
    === RUN   TestSourcesCommands
    --- PASS: TestSourcesCommands (0.90s)
    FAIL
  stdout_lines: <omitted>
```

### PR DESCRIPTION
**Pull request by teg**
qcow2, unlike ami, is guaranteed to exist on all the architectures we
support.

Also, now that we preserve the cache, make two composes, rather than
just one. This verifies that nothing breaks horribly just because the
cache not being cold. The fact that we have a cache at all should make
this tolerably fast.

This should fix #693.

Signed-off-by: Tom Gundersen <teg@jklm.no>

### CODE REVIEW

File: cmd/osbuild-tests/main_test.go [hunk 1]
```diff
@@ -73,9 +73,13 @@ func TestComposeCommands(t *testing.T) {
 	defer os.Remove(uuid.String() + "-logs.tar")
 
 	runComposer(t, "compose", "image", uuid.String())
-	_, err = os.Stat(uuid.String() + "-image.vhdx")
-	require.NoError(t, err, "'%s-image.vhdx' not found", uuid.String())
-	defer os.Remove(uuid.String() + "-image.vhdx")
+	_, err = os.Stat(uuid.String() + "-image.qcow2")
+	require.NoError(t, err, "'%s-image.qcow2' not found", uuid.String())
+	defer os.Remove(uuid.String() + "-image.qcow2")
```
Comment (larskarlitski) [inline cmd/osbuild-tests/main_test.go:78]: Oops I missed this one: `osbuild-tests` is failing because the qcow2 name is `-disk.qcow2`.

Comment (teg) [reply cmd/osbuild-tests/main_test.go]: Thanks!

**Comment by teg** [comment]
Force pushed to fix @larskarlitski's comment.

**Comment by teg** [comment]
Rebased to pick up CI fixes.
