### PR TITLE
Fix iot-installer build via the cloud API

### LINKED ISSUE #3125: Fedora IoT Rawhide compose is failing with  "Received empty package specs" (from compose-status.json)
**Describe the bug**
Fedora Rawhide compose is failing with the error (from compose-status.json):

reason  "Received empty package specs"
reason  "Manifest dependency failed"

Koji Task:
https://koji.fedoraproject.org/koji/taskinfo?taskID=93976262

Full compose logs:
https://kojipkgs.fedoraproject.org/compose/iot/Fedora-IoT-38-20221108.0/

**Environment**
 *  Fedora Koji
 
**To Reproduce**

To manually reproduce the error:
koji osbuild-image Fedora-IoT 38 fedora-38 f38-candidate x86_64 --repo='https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20221109.n.0/compose/Everything/x86_64/os/' --ostree-url='http://kojipkgs.fedoraproject.org/compose/iot/repo/' --ostree-ref='fedora/devel/$arch/iot' --image-type iot-installer --release 38.20221109.1 --skip-tag

https://koji.fedoraproject.org/koji/taskinfo?taskID=93978382

**Expected behavior**
Completed task in koji.

### PR DESCRIPTION
**Pull request by ondrejbudai**
8fdd1587997dbf091dd69a426bb44ef1c9abcfd1 modified the Cloud API to resolve
ostree commits using a separate job. This change caused the API handler
to call PackageSets without any ostree options (because they are not resolved
yet).

Unfortunately, the new implementation of PackageSets initializes the manifest.
The initialization checks the options and if the type is iot-installer and
it doesn't have the fetch checksum for IoT, it just returns an error.

To work around this (we need an initialized manifest to create the chains),
this commit just gives the initialization method a dummy checksum. The ostree
options currently don't have any effect on the package sets, so this should
be fine.

In order to make this workaround at least slightly sane, a warning is printed,
there's a new test just for this behaviour and a long comment to remember to
delete these lines.

Fixes #3125 

This pull request includes:

- [x] adequate testing for the new functionality or fixed issue

### CODE REVIEW

File: internal/distro/fedora/distro.go [hunk 1]
```diff
@@ -536,6 +538,24 @@ func (t *imageType) PackageSets(bp blueprint.Blueprint, options distro.ImageOpti
 		}
 	}
 
+	// In case of Cloud API, this method is called before the ostree commit
+	// resolved. Unfortunately, initializeManifest when called for an ostree
+	// installer returns an error.
```
Comment (achilleas-k) [inline internal/distro/fedora/distro.go:543]: typo: `commit is resolved`

File: internal/distro/fedora/distro.go [hunk 2]
```diff
@@ -536,6 +538,24 @@ func (t *imageType) PackageSets(bp blueprint.Blueprint, options distro.ImageOpti
...
+	//
+	// Work around this by providing a dummy FetchChecksum to convince the
+	// method that it's fine to initialize the manifest. Note that the ostree
+	// content has no effect on the package sets, so this is fine.
+	//
+	// See: https://github.com/osbuild/osbuild-composer/issues/3125
+	//
+	// TODO: Remove me when it's possible to initialize the get the package
+	//       set chain without resolving he ostree reference before. Also
+	//       remove the test for this workaround
```
Comment (achilleas-k) [inline internal/distro/fedora/distro.go:553]: typo: `possible to get the package set chain`

**Review by achilleas-k — APPROVED** [review]
LGTM.  Typos in the comments but nbd.

File: internal/distro/fedora/distro.go (hunk 1 above)
Comment (ondrejbudai) [reply internal/distro/fedora/distro.go]: fixed, thanks!

File: internal/distro/fedora/distro.go (hunk 2 above)
Comment (ondrejbudai) [reply internal/distro/fedora/distro.go]: fixed, thanks!

**Comment by ondrejbudai** [comment]
Your typo concerns were fixed. :)

**Review by achilleas-k — APPROVED** [review]
